### ISSUE TITLE
请问一下大佬们，我想了解一下接口响应统计中间件，相关具体代码在哪里呢？有没有一些推荐的参考demo 或者 学习资料哈～ （本人MQ小白一枚）

### ISSUE THREAD

**Issue by xqinwl** [fsd-nodejs/service-mw2#106]

**Comment by waitingsong** [comment]
可以参考 https://github.com/fsd-nodejs/service-mw2/#jaeger-%E9%93%BE%E8%B7%AF%E8%BF%BD%E8%B8%AA

**Comment by xqinwl** [comment]
> 可以参考 https://github.com/fsd-nodejs/service-mw2/#jaeger-%E9%93%BE%E8%B7%AF%E8%BF%BD%E8%B8%AA

那幅图的手写字看不太清，请问有没有更清晰一点的流程图吖。或者大佬您能告诉我具体的实现在哪，我可以去查阅一下源码，麻烦您了！！！

**Comment by waitingsong** [comment]
简单说：引入 @mw-components/jaeger 链路追踪中间件，配置好采集、上报参数，然后到统计界面查看。
不知道是否满足你的需求。

**Comment by xqinwl** [comment]
好的，那我有一些思路了，谢谢哈
