### ISSUE TITLE
会计划增加部署最佳实践吗？

### ISSUE THREAD

**Issue by yangcecode** [fsd-nodejs/service-mw2#107]
我是一个前端，学习代码可以但是代码写好以后部署就遇到了麻烦

**Comment by tkvern** [comment]
是什么环节出了问题，能详细描述下，提供下错误的信息。

**Comment by tkvern** [comment]
这个的部署，有多种方式，按照官方的文档应该就可以。
https://midwayjs.org/docs/deployment

**Comment by tkvern** [comment]
如果你想 docker 部署话，可以看项目文档打包成 image 去做部署

**Comment by yangcecode** [comment]
> 如果你想 docker 部署话，可以看项目文档打包成 image 去做部署
谢谢 我部署上去了 以后等生产遇到问题我再提问吧
