### ISSUE TITLE
redis连接超时

### ISSUE THREAD

**Issue by guojoa** [fsd-nodejs/service-mw2#26]
redis设置无密码和有密码都测试了，都提示连接超时

2020-12-24 12:23:49,281 ERROR 21990 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (/home/guo/development/javascript/midwayjs/project/service-mw2/node_modules/_ioredis@4.19.4@ioredis/built/redis/index.js:308:37)                                      
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
name: "ETIMEDOUTError"

**Comment by tkvern** [comment]
启动的是哪个环境？配置 redis 的 IP 能正常访问吗

**Comment by tkvern** [comment]
![image](https://user-images.githubusercontent.com/10667077/103070630-e4584f80-45fc-11eb-9654-4fd55476046c.png)
需要确认你的 Redis  服务已经启动

**Comment by guojoa** [comment]
可以确定启动了，我单独创建一个项目，安装egg-redis后是正常的，以下是我的代码

import { Controller, Get, Provide } from '@midwayjs/decorator';
import { Context } from 'egg';

@Provide()
@Controller('/')
export class HomeController {
  @Get('/')
  async home() {
    return 'Hello Midwayjs!';
  }

  @Get('/test')
  async test(ctx:Context) {
    console.log('ctx',await ctx.app.redis.get('a'));
    const a = await ctx.app.redis.get('a')
    return 'my test ' + a;
  }
}
网页访问test方法能正常返回redis设置的值

**Comment by tkvern** [comment]
![image](https://user-images.githubusercontent.com/10667077/103183038-10205180-48eb-11eb-8352-fd39ba221ded.png)
我复现了你说的问题，一般这种情况，需要修改config文件中配置的IP

**Comment by guojoa** [comment]
默认是127.0.0.1，我改成localhost,或192.168.1.x。还是不行

**Comment by tkvern** [comment]
可能需要你自行排查下哪个环节有问题。

**Comment by NiBoTe** [comment]
我的也连不上Redis，都修改了也不行，不知道为啥

**Comment by tkvern** [comment]
麻烦提供一下复现步骤

**Comment by NiBoTe** [comment]
我别的项目也在使用，IP 和 端口啥的都是一样。另外一个项目没有问题。




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fsd-nodejs/service-mw2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 上午10:51
收件人:&nbsp;"fsd-nodejs/service-mw2"<service-mw2@noreply.github.com&gt;;
抄送:&nbsp;"贾冰"<851080120@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fsd-nodejs/service-mw2] redis连接超时 (#26)





 
麻烦提供一下复现步骤

**Comment by NiBoTe** [comment]
麻烦帮忙看一下。




&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "fsd-nodejs/service-mw2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 上午10:51
收件人:&nbsp;"fsd-nodejs/service-mw2"<service-mw2@noreply.github.com&gt;;
抄送:&nbsp;"贾冰"<851080120@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fsd-nodejs/service-mw2] redis连接超时 (#26)





 
麻烦提供一下复现步骤

**Comment by NiBoTe** [comment]
我直接修改了 config.default.ts 文件中的配置
![image](https://user-images.githubusercontent.com/24713845/103392797-81197080-4b5a-11eb-9ccb-f2f77aa342f9.png)

**Comment by tkvern** [comment]
本地开发你需要修改config.local.ts这个文件
