### ISSUE TITLE
中间件redis启动报错（更新了对rabbitmq的支持之后）

### ISSUE THREAD

**Issue by ronaldoxzb** [fsd-nodejs/service-mw2#89]
![image](https://user-images.githubusercontent.com/30582262/127794291-78b0cb52-a529-4c31-aa07-fb8de27ffc61.png)
麻烦看下

**Comment by tkvern** [comment]
好像是依赖的问题，一会我更新下

**Comment by tkvern** [comment]
已经修复，重新拉下master的代码

**Comment by ronaldoxzb** [comment]
哪里问题哦

**Comment by tkvern** [comment]
tsconfig 的配置问题

**Comment by ronaldoxzb** [comment]
好的 谢谢
