### ISSUE TITLE
目录结构和midway（v2）文档里的不一致

### ISSUE THREAD

**Issue by cckowin** [fsd-nodejs/service-mw2#9]
目录结构和midway（v2）文档里的不一致，很多文档里推荐放在src目录下的都放在了app目录下下，如果用eggjs作为上层框架的话更推荐哪种目录结构啊

**Comment by tkvern** [comment]
midway可以灵活配置目录，如果是使用eggjs作为上层框架的话，我的建议是按照团队的约定达成一致。之前我们团队一直在使用eggjs。目前我选择的是跟eggjs保持一致的目录结构，这样一来就没有重新达成约定的成本。

**Comment by cckowin** [comment]
好的，谢谢，还有一个问题请教下，我从eggjs迁移到midway，schedule目录还能放在app下嘛，文档里是写放在src目录下的，说是放在src/app/schedule中会和eggjs本身的加载冲突

**Comment by tkvern** [comment]
暂时还没写schedule的案例，应该是兼容的
