### ISSUE TITLE
jwt问题

### ISSUE THREAD

**Issue by ronaldoxzb** [fsd-nodejs/service-mw2#91]
![image](https://user-images.githubusercontent.com/30582262/127798929-5af5e120-431f-4d06-8b11-f319b8882452.png)
大佬 接口如果不想用鉴权只能在这里配置么，不能像egg那样写在router中引入中间件么

**Comment by waitingsong** [comment]
是的，只能在这儿。支持通配（规则见上一行注释链接）

**Comment by ronaldoxzb** [comment]
好的 谢谢
