### ISSUE TITLE
对 jwt auth 示例的一点小小建议

### ISSUE THREAD

**Issue by singlebyted** [fsd-nodejs/service-mw2#94]
https://github.com/fsd-nodejs/service-mw2/blob/85f9db5f18fbb2857e3be0a222795c29ee4cbf0d/src/app/middleware/jwt-auth.ts#L14

这里建议把 `decode(...)` 换成 `verify(...)`，因为可能出现小白错误理解的情况，而且 auth 的场景也确实应该使用 verify 😅。

[Reference](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback)
> Warning: When the token comes from an untrusted source (e.g. user input or external requests), the returned decoded payload should be treated like any other user input; please make sure to sanitize and only work with properties that are expected
> 警告：当令牌来自不受信任的来源（例如用户输入或外部请求）时，应将返回的解码负载视为任何其他用户输入； 请确保进行消毒并仅使用预期的属性（纯机翻 😁）

**Comment by waitingsong** [comment]
这儿使用 `decode()` 应该是没问题的：
这个中间件依赖的 jwt 插件（目前是 egg-jwt，正在升级为 jwt midway 组件）自带（默认启用）的中间件会对 token 进行校验（`verify()`）。并且校验时机是在进入本中间件( jwt-auth.ts) 之前，确保 token 正确

当然，如果改为直接从 ctx.user （ jwt midway 组件是 ctx.jwtState.user ）上面直接取值就更安全了。

**Comment by singlebyted** [comment]
过了一遍大佬的插件代码，厘清楚了，感谢解答！😁
